# Generated by Django 3.2.9 on 2021-11-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imagespin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
