# Generated by Django 3.2.9 on 2021-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
