# Generated by Django 3.2.9 on 2021-12-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_pinuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinuser',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
