# Generated by Django 3.2.9 on 2021-12-03 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_pinuser_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinuser',
            old_name='following',
            new_name='following_me',
        ),
        migrations.AddField(
            model_name='pinuser',
            name='i_follows',
            field=models.ManyToManyField(related_name='i_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
